name: CI

on: 
  push:
  schedule:
  - cron: '5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: monitor blog
      run: curl -sSf https://dddd.cashwu.com > /dev/null
    - name: monitor es
      run: curl -sSf https://www.elephantshine.com/ > /dev/null
