name: Monitor

on: 
  push:
  schedule:
  - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: monitor blog
      continue-on-error: true
      run: curl -sSf https://dddd.cashwu.com > /dev/null
    - name: monitor es
      continue-on-error: true
      run: curl -sSf https://www.elephantshine.com/ > /dev/null
    - name: slack notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Monitor Report*'
        mention: 'here'
        mention_if: 'always'
        channel: '#general'
        url: ${{ secrets.SLACK_WEBHOOK }}
