name: Monitor

on: 
  push:
  schedule:
  - cron: '*/3 * * * *'

jobs:
  es:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: monitor es
      run: curl -sSf https://www.elephantshine.com/ > /dev/null
    - name: slack notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*ES Monitor Report*'
        mention_if: failure
        channel: '#general'
        url: ${{ secrets.SLACK_WEBHOOK }}
    

  blog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: monitor blog
      run: curl -sSf https://blog.cashwu.com > /dev/null
    - name: slack notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*BLOG Monitor Report*'
        mention_if: failure
        channel: '#general'
        url: ${{ secrets.SLACK_WEBHOOK }}
